/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModernUI;

import java.io.IOException;
import java.net.UnknownHostException;
import javax.swing.JOptionPane;

/**
 *
 * @author Zobayer
 */
public class Server extends javax.swing.JFrame {

    /**
     * Creates new form Errormsg
     */
    
    public Server() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        running.setVisible(false);
        runningmsg.setVisible(false);
        notRunning.setVisible(true);
        stopmsg.setVisible(true);
    }
    public Server(String msgToShow) {
        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        stop = new javax.swing.JButton();
        running = new javax.swing.JLabel();
        notRunning = new javax.swing.JLabel();
        run = new javax.swing.JButton();
        runningmsg = new javax.swing.JLabel();
        stopmsg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 10, true));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(300, 0, 30, 30);

        stop.setBackground(new java.awt.Color(255, 255, 255));
        stop.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        stop.setForeground(new java.awt.Color(0, 102, 204));
        stop.setText("Stop");
        stop.setBorder(null);
        stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stopMouseExited(evt);
            }
        });
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        jPanel1.add(stop);
        stop.setBounds(190, 150, 80, 30);

        running.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zobayer\\Documents\\NetBeansProjects\\ChattingApplication\\src\\ModernUI\\success1.png")); // NOI18N
        jPanel1.add(running);
        running.setBounds(20, 50, 60, 80);

        notRunning.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zobayer\\Documents\\NetBeansProjects\\ChattingApplication\\src\\ModernUI\\error2.jpg")); // NOI18N
        jPanel1.add(notRunning);
        notRunning.setBounds(20, 50, 60, 80);

        run.setBackground(new java.awt.Color(0, 102, 204));
        run.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        run.setForeground(new java.awt.Color(255, 255, 255));
        run.setText("Run");
        run.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                runMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                runMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                runMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                runMouseReleased(evt);
            }
        });
        run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runActionPerformed(evt);
            }
        });
        jPanel1.add(run);
        run.setBounds(60, 150, 80, 30);

        runningmsg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        runningmsg.setText("Server is Running");
        jPanel1.add(runningmsg);
        runningmsg.setBounds(100, 70, 210, 40);

        stopmsg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        stopmsg.setText("Server not Running");
        jPanel1.add(stopmsg);
        stopmsg.setBounds(100, 70, 190, 40);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zobayer\\Documents\\NetBeansProjects\\ChattingApplication\\src\\ModernUI\\popupMassege.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 330, 200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopMouseEntered
        // TODO add your handling code here:
        stop.setBackground(new java.awt.Color(0, 102, 204));
        stop.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_stopMouseEntered

    private void stopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopMouseExited
        // TODO add your handling code here:
        stop.setBackground(new java.awt.Color(255, 255, 255));
        stop.setForeground(new java.awt.Color(0, 102, 204));
    }//GEN-LAST:event_stopMouseExited

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        // TODO add your handling code here:
        Server s = new Server();
        this.setVisible(false);
        s.setVisible(true);
        this.dispose();
        
        running.setVisible(false);
        runningmsg.setVisible(false);
        notRunning.setVisible(true);
        stopmsg.setVisible(true);
    }//GEN-LAST:event_stopActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void runMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_runMouseEntered
        // TODO add your handling code here:
        run.setBackground(new java.awt.Color(255, 255, 255));
        run.setForeground(new java.awt.Color(0, 102, 204));
    }//GEN-LAST:event_runMouseEntered

    private void runMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_runMouseExited
        // TODO add your handling code here:
        run.setBackground(new java.awt.Color(0, 102, 204));
        run.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_runMouseExited

    private void runActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runActionPerformed
        // TODO add your handling code here:
        
        try {
            ChatServer cs = new ChatServer();
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Server Can't run");
        }
        notRunning.setVisible(false);
        stopmsg.setVisible(false);
        running.setVisible(true);
        runningmsg.setVisible(true);
    }//GEN-LAST:event_runActionPerformed

    private void runMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_runMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_runMouseClicked

    private void runMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_runMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_runMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel notRunning;
    private javax.swing.JButton run;
    private javax.swing.JLabel running;
    private javax.swing.JLabel runningmsg;
    private javax.swing.JButton stop;
    private javax.swing.JLabel stopmsg;
    // End of variables declaration//GEN-END:variables
}
