/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModernUI;

import java.io.IOException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Zobayer
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    int xMouse, yMouse;
    public Signup() {
        
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    boolean findChar(String s, char ch) {
        int conn = 0;
        for (int i = 0; i < s.length(); ++i) {
            if (s.charAt(i) == '@') ++conn;
        }
        if (conn == 1) return true;
        return false;
    } 
    Connection conn;
    Statement st;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fName = new javax.swing.JFormattedTextField();
        emailAdd = new javax.swing.JFormattedTextField();
        DOB = new javax.swing.JTextField();
        pWord = new javax.swing.JPasswordField();
        rpWord = new javax.swing.JPasswordField();
        register = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(register.isDefaultButton());
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(680, 390));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Castellar", 1, 31)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign Up");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(390, 20, 170, 40);

        fName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        fName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fName.setText("Enter your full name");
        fName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fNameFocusLost(evt);
            }
        });
        fName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fNameMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fNameMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fNameMouseReleased(evt);
            }
        });
        fName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameActionPerformed(evt);
            }
        });
        jPanel1.add(fName);
        fName.setBounds(290, 70, 340, 31);

        emailAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        emailAdd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailAdd.setText("Enter email");
        emailAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailAdd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailAddFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailAddFocusLost(evt);
            }
        });
        emailAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emailAddMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                emailAddMouseReleased(evt);
            }
        });
        emailAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailAddActionPerformed(evt);
            }
        });
        jPanel1.add(emailAdd);
        emailAdd.setBounds(290, 120, 340, 31);

        DOB.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        DOB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DOB.setText("Date of Birth");
        DOB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        DOB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DOBFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DOBFocusLost(evt);
            }
        });
        DOB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DOBMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DOBMouseReleased(evt);
            }
        });
        jPanel1.add(DOB);
        DOB.setBounds(290, 170, 340, 31);

        pWord.setFont(new java.awt.Font("Serif", 1, 10)); // NOI18N
        pWord.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pWord.setText("password");
        pWord.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        pWord.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pWordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pWordFocusLost(evt);
            }
        });
        pWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pWordMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pWordMouseReleased(evt);
            }
        });
        jPanel1.add(pWord);
        pWord.setBounds(290, 220, 340, 31);

        rpWord.setFont(new java.awt.Font("Serif", 1, 10)); // NOI18N
        rpWord.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rpWord.setText("repasswo");
        rpWord.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        rpWord.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rpWordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rpWordFocusLost(evt);
            }
        });
        rpWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rpWordMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rpWordMouseReleased(evt);
            }
        });
        jPanel1.add(rpWord);
        rpWord.setBounds(290, 270, 340, 31);

        register.setBackground(new java.awt.Color(255, 255, 255));
        register.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        register.setText("Register");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerMouseExited(evt);
            }
        });
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel1.add(register);
        register.setBounds(310, 330, 117, 33);

        back.setBackground(new java.awt.Color(0, 102, 204));
        back.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(500, 330, 117, 33);

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(35, 35));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(640, 0, 40, 35);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ModernUI/multy-user.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 90, 120, 150);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Welcome to Massenger");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 250, 236, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ModernUI/largeBackground.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 680, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameActionPerformed

    private void emailAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailAddActionPerformed

    private void fNameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fNameMouseReleased
        // TODO add your handling code here:
        fName.setText(null);
    }//GEN-LAST:event_fNameMouseReleased

    private void emailAddMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailAddMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_emailAddMouseReleased

    private void DOBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DOBMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBMouseReleased

    private void pWordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pWordMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_pWordMouseReleased

    private void rpWordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rpWordMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_rpWordMouseReleased

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        String s1, s2, s3, s4, s5;
        s1 = String.valueOf(pWord.getPassword());
        s2 = String.valueOf(rpWord.getPassword());
        s3 = emailAdd.getText();
        s4 = fName.getText();
        s5 = DOB.getText();
        
        if (!s1.equals(s2)) {
            JOptionPane.showMessageDialog(null, "Password not match!");
        }
        else if(!findChar(s3, '@')) {
            JOptionPane.showMessageDialog(null, "Email is not correct");
        }
        else if (s4.equals("")) {
            JOptionPane.showMessageDialog(null, "Name is empty");
        }
        else if (s5.equals("")){
            JOptionPane.showMessageDialog(null, "Date of Birth is empty");
        }
        else {
            // Now all data can store in database
            String s = fName.getText();
            String p1 = String.valueOf(pWord.getPassword());
            
            try{
                conn = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/massenger", "root", "seagoldbag");
                st = (com.mysql.jdbc.Statement) conn.createStatement();
                String sql = "insert into userlogin (ID, UserName, Password) values ('CSE', '"+s+"', '"+p1+"');";
                
                st.executeUpdate(sql);
                this.setVisible(false);
                //JOptionPane.showMessageDialog(null, "You are registered now.\nYou can log in.");
                
                Successmsg l = new Successmsg("You are registered now.\nYou can log in.");
                l.setVisible(true);
                
                this.dispose();
                
            }
            catch(Exception e) {
                JOptionPane.showMessageDialog(null, "User name alread have.\nTry different user name");
            }
        }
    }//GEN-LAST:event_registerActionPerformed

    private void fNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fNameMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameMouseExited

    private void emailAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailAddMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_emailAddMouseExited

    private void DOBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DOBMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBMouseExited

    private void pWordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pWordMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pWordMouseExited

    private void rpWordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rpWordMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_rpWordMouseExited

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void fNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        // TODO add your handling code here:
        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setForeground(new java.awt.Color(0, 102, 204));
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        // TODO add your handling code here:
        back.setBackground(new java.awt.Color(0, 102, 204));
        back.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_backMouseExited

    private void registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseEntered
        // TODO add your handling code here:
        register.setBackground(new java.awt.Color(0, 102, 204));
        register.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_registerMouseEntered

    private void registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseExited
        // TODO add your handling code here:
        register.setBackground(new java.awt.Color(255, 255, 255));
        register.setForeground(new java.awt.Color(0, 102, 204));
    }//GEN-LAST:event_registerMouseExited

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jPanel2MouseClicked

    private void fNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fNameFocusLost
        // TODO add your handling code here:
        String s = fName.getText();
        if (s.equals("")) {
            fName.setText("Enter your full name");
        }
    }//GEN-LAST:event_fNameFocusLost

    private void fNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fNameFocusGained
        // TODO add your handling code here:
        String s = fName.getText();
        if (s.equals("Enter your full name")) {
            fName.setText("");
        }
    }//GEN-LAST:event_fNameFocusGained

    private void emailAddFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailAddFocusLost
        // TODO add your handling code here:
        String s = emailAdd.getText();
        if (s.equals("")) {
            emailAdd.setText("Enter email");
        }
    }//GEN-LAST:event_emailAddFocusLost

    private void emailAddFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailAddFocusGained
        // TODO add your handling code here:
        String s = emailAdd.getText();
        if (s.equals("Enter email")) {
            emailAdd.setText("");
        }
    }//GEN-LAST:event_emailAddFocusGained

    private void DOBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBFocusLost
        // TODO add your handling code here:
        String s = DOB.getText();
        if (s.equals("")) {
            DOB.setText("Date of Birth");
        }
    }//GEN-LAST:event_DOBFocusLost

    private void DOBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBFocusGained
        // TODO add your handling code here:
        String s = DOB.getText();
        if (s.equals("Date of Birth")) {
            DOB.setText("");
        }
    }//GEN-LAST:event_DOBFocusGained

    private void pWordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pWordFocusLost
        // TODO add your handling code here:
        String s = String.valueOf(pWord.getPassword());
        if (s.equals("")) {
            pWord.setText("password");
        }
    }//GEN-LAST:event_pWordFocusLost

    private void pWordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pWordFocusGained
        // TODO add your handling code here:
        String s = String.valueOf(pWord.getPassword());
        if (s.equals("password")) {
            pWord.setText("");
        }
    }//GEN-LAST:event_pWordFocusGained

    private void rpWordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rpWordFocusLost
        // TODO add your handling code here:
        String s = String.valueOf(rpWord.getPassword());
        if (s.equals("")) {
            rpWord.setText("repasswo");
        }
    }//GEN-LAST:event_rpWordFocusLost

    private void rpWordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rpWordFocusGained
        // TODO add your handling code here:
        String s = String.valueOf(rpWord.getPassword());
        if (s.equals("repasswo")) {
            rpWord.setText("");
        }
    }//GEN-LAST:event_rpWordFocusGained

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
        // TODO add your handling code here:
        String s = fName.getText();
        if (s.equals("")) {
            fName.setText("Enter your full name");
        }
    }//GEN-LAST:event_jPanel1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DOB;
    private javax.swing.JButton back;
    private javax.swing.JFormattedTextField emailAdd;
    private javax.swing.JFormattedTextField fName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField pWord;
    private javax.swing.JButton register;
    private javax.swing.JPasswordField rpWord;
    // End of variables declaration//GEN-END:variables
}
